### ISSUE TITLE
Use color of entity even no corresponding layer is found

### ISSUE THREAD

**Issue by apriljunge** [bjnortier/dxf#139] opened 2024-04-10 16:54 UTC
In `.toPolyLines()` the color of the entity is only parsed when a matching layer is found.
If theres no layer found, the color is set to black even when the entity has an color attribute. Is this intended?

https://github.com/skymakerolof/dxf/blob/9895f4f23dbda0ce504dc7b5cc1715a3c66f5ba8/src/toPolylines.js#L14-L25

**Comment by skymakerolof** [comment] 2024-05-27 05:19
It seems strange that the color attribute of the entity is only parsed when a matching layer is found, and defaults to black otherwise, even if the entity has a specified color. I'm not entirely sure about the intended behavior here, but it does raise some questions. A pull request to address this would be welcome.

**Comment by skymakerolof** [comment] 2024-08-30 11:53
https://github.com/skymakerolof/dxf/pull/140 Released as 5.1.1

**Closed as completed by skymakerolof** 2024-08-30 11:53 UTC
